// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLcrY-iKh0H_f7V0OYPtVmcLlNmsz9To0',
    appId: '1:790913303284:web:aeff9f6a5039d79be094a1',
    messagingSenderId: '790913303284',
    projectId: 'flutix-4a054',
    authDomain: 'flutix-4a054.firebaseapp.com',
    storageBucket: 'flutix-4a054.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBM1aJyT9ldVmi8dB8R4EpEtxQz0uXCW2g',
    appId: '1:790913303284:android:68b0e29fc1f02ed3e094a1',
    messagingSenderId: '790913303284',
    projectId: 'flutix-4a054',
    storageBucket: 'flutix-4a054.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdk5sYDASQQ35fKevOD05bmJa9q_1GGj8',
    appId: '1:790913303284:ios:e8c9484f4ed6e005e094a1',
    messagingSenderId: '790913303284',
    projectId: 'flutix-4a054',
    storageBucket: 'flutix-4a054.appspot.com',
    iosClientId: '790913303284-2o48riph05fbvgoi18msub24hapcoifa.apps.googleusercontent.com',
    iosBundleId: 'com.sahibulnf.flutix',
  );
}
